"""empty message

Revision ID: 0b367b8b66be
Revises: 0e7b220b726e
Create Date: 2021-12-14 01:17:44.257936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b367b8b66be'
down_revision = '0e7b220b726e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_list_ibfk_2', 'favorite_list', type_='foreignkey')
    op.drop_constraint('favorite_list_ibfk_3', 'favorite_list', type_='foreignkey')
    op.drop_column('favorite_list', 'starships_id')
    op.drop_column('favorite_list', 'planets_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_list', sa.Column('planets_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorite_list', sa.Column('starships_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorite_list_ibfk_3', 'favorite_list', 'starships', ['starships_id'], ['id'])
    op.create_foreign_key('favorite_list_ibfk_2', 'favorite_list', 'planets', ['planets_id'], ['id'])
    # ### end Alembic commands ###
