"""empty message

Revision ID: 0e7b220b726e
Revises: 1ab8c0995394
Create Date: 2021-12-11 23:28:00.507180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e7b220b726e'
down_revision = '1ab8c0995394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('img', sa.String(length=250), nullable=True))
    op.drop_column('people', 'url')
    op.add_column('planets', sa.Column('img', sa.String(length=250), nullable=True))
    op.add_column('starships', sa.Column('img', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('starships', 'img')
    op.drop_column('planets', 'img')
    op.add_column('people', sa.Column('url', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('people', 'img')
    # ### end Alembic commands ###
