"""empty message

Revision ID: 1ab8c0995394
Revises: 0df5268b9982
Create Date: 2021-12-11 17:51:53.412451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab8c0995394'
down_revision = '0df5268b9982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'url')
    # ### end Alembic commands ###
