"""empty message

Revision ID: 89e7ca0ed27d
Revises: 0b367b8b66be
Create Date: 2021-12-14 01:23:52.407945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e7ca0ed27d'
down_revision = '0b367b8b66be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_list', sa.Column('planets_id', sa.Integer(), nullable=True))
    op.add_column('favorite_list', sa.Column('starships_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite_list', 'starships', ['starships_id'], ['id'])
    op.create_foreign_key(None, 'favorite_list', 'planets', ['planets_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_list', type_='foreignkey')
    op.drop_constraint(None, 'favorite_list', type_='foreignkey')
    op.drop_column('favorite_list', 'starships_id')
    op.drop_column('favorite_list', 'planets_id')
    # ### end Alembic commands ###
