"""empty message

Revision ID: 977f664581e9
Revises: 5a33f8c83c10
Create Date: 2021-12-11 14:31:34.266044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977f664581e9'
down_revision = '5a33f8c83c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
