"""empty message

Revision ID: fe3710e3f275
Revises: c2b3c5691b3d
Create Date: 2021-12-11 13:40:51.859944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe3710e3f275'
down_revision = 'c2b3c5691b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('people', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('people', 'eye_color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'eye_color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('people', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('people', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
